const pathRouter = {
    empty: '',
    dashboard: '/',
    login: '/login',
    register: '/register',
    logout: '/logout',
    attendance: '/attendance/today',
    attendance_qrcode: '/attendance/:id/today',
    attendance_history: '/attendance/history',
    attendance_history_detail: '/attendance/:id/history',
    user: '/user',
    user_create: '/user/create',
    user_teacher: '/user/teacher',
    user_teacher_create: '/user/teacher/create',
    module: '/module',
    module_create: '/module/create',
    module_add_user: '/module/:id/user',
    shift: '/shift',
    shift_create: '/shift/create',
    shift_add_user: '/shift/:id/user',
}
export default pathRouter
